services:
  api:
    build: .
    ports:
      - "8000:5000"

  database:
    image: mysql:8.3
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: cv24